return {
  "zaldih/themery.nvim",
  lazy = false,
  opts = {
    themes = {
      "everforest",
      "nord",
      "catppuccin-frappe",
      "catppuccin-latte",
      "catppuccin-macchiato",
      "catppuccin-mocha",
      "tokyonight-day",
      "tokyonight-night",
      "tokyonight-storm",
      "tokyonight-moon",
      "kanagawa-wave",
      "kanagawa-dragon",
      "kanagawa-lotus",
      "Nightfox",
      "Dawnfox",
      "Duskfox",
      "Dayfox",
      "Nordfox",
      "Terafox",
      "Carbonfox",
    },
  },
}
